### ISSUE TITLE
Some creature entries are incomplete (missing a section)

### ISSUE THREAD

**Issue by majesstic** [Radai/dnd5tools#16]
Some creature entries are missing the Traits and/or Actions info section.

Known impacted creatures: Wolf, Dire Wolf, Swarm of Insects, Giant Crab... there are likely others as well.

Windows 10 build 10586
Reproduced in Chrome 51.x, IE11, and MS Edge

An example creature entry, missing the "Actions" section (should have a Bite action):

![missing_section](https://cloud.githubusercontent.com/assets/20364670/16705515/40f7911a-4549-11e6-9f89-837cde852f42.png)

**Comment by Radai** [comment]
Yeah, this is due to how poorly I'm attempting to parse the embedded action objects. If you open the console in Chrome and type 'compendium' it'll show you the object and you can explore the actual stuffs in there if you'd like. I'll get to fixing it when I create cards that are specifically designed for each type of thing (monster, spell, etc). Thanks for reporting it though! Sorry it sucks sometimes! :D

I'll keep this open as a reminder ;)
